// GENERATED by central/scripts/gen_map_fallback.py from the agent's
// data/static/map_config.json (SquadCalc's map extents). Do not edit
// by hand — regenerate instead, so this cannot drift from what the
// recorder itself uses.
//
// Used only when a recording carries no `layer` block, which happens
// when a community names its scrim layer after itself and the
// recorder's per-layer lookup misses. Whole-map extent paired with
// the whole-map image, so the picture and the bounds agree.
export interface FallbackMap {
  texture: string;
  topLeft: { x: number; y: number };
  bottomRight: { x: number; y: number };
}

export const MAP_FALLBACKS: ReadonlyMap<string, FallbackMap> = new Map([
  ["AlBasrah", { texture: "AlBasrah", topLeft: { x: -200000, y: -200000 }, bottomRight: { x: 200000, y: 200000 } }],
  ["Anvil", { texture: "Anvil", topLeft: { x: -204000, y: -204000 }, bottomRight: { x: 102000, y: 102000 } }],
  ["Belaya", { texture: "Belaya", topLeft: { x: -195400, y: -208000 }, bottomRight: { x: 195000, y: 182500 } }],
  ["BlackCoast", { texture: "BlackCoast", topLeft: { x: -229999.515625, y: -212746.78125 }, bottomRight: { x: 229998.46875, y: 247251.0625 } }],
  ["Chora", { texture: "Chora", topLeft: { x: -246400, y: -266400 }, bottomRight: { x: 159990, y: 140000 } }],
  ["Fallujah", { texture: "Fallujah", topLeft: { x: -131500, y: -154500 }, bottomRight: { x: 169000, y: 146000 } }],
  ["FoolsRoad", { texture: "FoolsRoad", topLeft: { x: -132576.921875, y: -132576.921875 }, bottomRight: { x: 44805.078125, y: 44805.078125 } }],
  ["GooseBay", { texture: "GooseBay", topLeft: { x: -201657.890625, y: -201674.84375 }, bottomRight: { x: 201523.078125, y: 201503.078125 } }],
  ["Gorodok", { texture: "Gorodok_fmodel", topLeft: { x: -203199, y: -203200 }, bottomRight: { x: 203201, y: 203200 } }],
  ["Harju", { texture: "Harju", topLeft: { x: -201600, y: -201600 }, bottomRight: { x: 201600, y: 201600 } }],
  ["Jensen", { texture: "Jensen", topLeft: { x: -200400, y: -200400 }, bottomRight: { x: 200400, y: 200400 } }],
  ["Kamdesh", { texture: "Kamdesh", topLeft: { x: -201600, y: -201600 }, bottomRight: { x: 201600, y: 201600 } }],
  ["Kohat", { texture: "Kohat", topLeft: { x: -230000, y: -230000 }, bottomRight: { x: 231700, y: 231700 } }],
  ["Kokan", { texture: "Kokan", topLeft: { x: -107634.9375, y: -107566.75 }, bottomRight: { x: 142013.671875, y: 142013.671875 } }],
  ["Lashkar", { texture: "Lashkar", topLeft: { x: -216700, y: -216700 }, bottomRight: { x: 216700, y: 216700 } }],
  ["Logar", { texture: "Logar_fmodel", topLeft: { x: -88145.140625, y: -113238.7578125 }, bottomRight: { x: 87978.328125, y: 62921.7109375 } }],
  ["Manicouagan", { texture: "Manicouagan", topLeft: { x: -201657.890625, y: -201674.84375 }, bottomRight: { x: 201657.890625, y: 201674.84375 } }],
  ["Mestia", { texture: "Mestia", topLeft: { x: -120000, y: -110000 }, bottomRight: { x: 120000, y: 130000 } }],
  ["Mutaha", { texture: "Mutaha", topLeft: { x: -93500, y: -114000 }, bottomRight: { x: 182000, y: 161500 } }],
  ["Narva", { texture: "Narva", topLeft: { x: -138970.6875, y: -140207.4375 }, bottomRight: { x: 141029.375, y: 139792.515625 } }],
  ["Pacific", { texture: "Pacific", topLeft: { x: -201600, y: -201600 }, bottomRight: { x: 201600, y: 201600 } }],
  ["Sanxian", { texture: "Sanxian", topLeft: { x: -230000, y: -205000 }, bottomRight: { x: 230000, y: 255000 } }],
  ["Skorpo", { texture: "Skorpo", topLeft: { x: -360150, y: -360150 }, bottomRight: { x: 324850, y: 324850 } }],
  ["Sumari", { texture: "Sumari", topLeft: { x: -63973.92578125, y: -44728.078125 }, bottomRight: { x: 66033.578125, y: 85297.234375 } }],
  ["Tallil", { texture: "Tallil", topLeft: { x: -234000, y: -234000 }, bottomRight: { x: 234000, y: 234000 } }],
  ["Yehorivka", { texture: "Yehorivka", topLeft: { x: -330197.40625, y: -330199.5 }, bottomRight: { x: 304803, y: 304800 } }],
]);
