// The commander scenarios: one recording per viewer rule, playable in the
// browser with no server, no live match and no .sqrx.
//
// The fixtures themselves are generated by `generate.mjs` beside this file —
// that script is the readable form of each scenario and the JSON is its
// output. Add a scenario there, run it, and add a line to LOADERS below; the
// missing-file case is then a compile error rather than a blank page.
//
// The manifest is imported eagerly (a few hundred bytes: names, titles and
// the rule each demonstrates) and every scenario's frames are imported on
// demand, so opening the picker costs nothing and opening a scenario costs
// only that scenario.

import manifest from "./manifest.json" with { type: "json" };
import type { RecordingLine } from "../../replayReconstruct";

export interface ScenarioMeta {
  /** The url value: `?scenario=<name>`. */
  name: string;
  title: string;
  /** What the reviewer is looking at. */
  shows: string;
  /** The spec rule it demonstrates, cited by section. */
  rule: string;
  lineCount: number;
}

export const SCENARIOS: ScenarioMeta[] = manifest as ScenarioMeta[];

type Loader = () => Promise<{ default: unknown }>;

const LOADERS: Record<string, Loader> = {
  "request-pending": () => import("./request-pending.json"),
  "request-approved-with-twin": () => import("./request-approved-with-twin.json"),
  "request-deleted": () => import("./request-deleted.json"),
  "footprint-uav-coverage": () => import("./footprint-uav-coverage.json"),
  "footprint-static-barrage": () => import("./footprint-static-barrage.json"),
  "footprint-creep-path": () => import("./footprint-creep-path.json"),
  "footprint-strike-line": () => import("./footprint-strike-line.json"),
  "footprint-mortar-radius": () => import("./footprint-mortar-radius.json"),
  "footprint-aim-line": () => import("./footprint-aim-line.json"),
  "vote-in-progress": () => import("./vote-in-progress.json"),
  "seat-cooling-and-ready": () => import("./seat-cooling-and-ready.json"),
  "commander-change-restamp": () => import("./commander-change-restamp.json"),
  "commander-step-down": () => import("./commander-step-down.json"),
  "uav-shot-down": () => import("./uav-shot-down.json"),
  "drone-recon-life": () => import("./drone-recon-life.json"),
  "drone-commander-call": () => import("./drone-commander-call.json"),
};

/** The raw recording lines of one scenario — full frames and 4 Hz position
 *  lines interleaved, exactly as a `.sqrx` carries them, so the caller folds
 *  them with the same reconstructor a real recording goes through.
 *
 *  `null` for a name nothing knows: a stale link should say so rather than
 *  quietly showing the wrong scenario. */
export async function loadScenarioLines(
  name: string,
): Promise<RecordingLine[] | null> {
  const load = LOADERS[name];
  if (!load) return null;
  const mod = await load();
  const doc = mod.default as { lines?: RecordingLine[] } | undefined;
  return doc?.lines ?? null;
}
